version: '3'
services:
  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=your_api_key_here
      - DD_SITE=datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
